# Generated by Django 2.2.1 on 2019-05-11 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Alert_type', models.CharField(max_length=2)),
                ('name', models.CharField(max_length=30)),
                ('time', models.DateTimeField()),
                ('location', models.CharField(max_length=30)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(blank=True, max_length=60)),
                ('username', models.CharField(blank=True, max_length=30)),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('language', models.CharField(blank=True, max_length=30)),
                ('country', models.CharField(blank=True, max_length=30)),
                ('question_5', models.CharField(blank=True, max_length=30)),
                ('question_6', models.CharField(blank=True, max_length=30)),
                ('question_7', models.CharField(blank=True, max_length=30)),
                ('question_8', models.CharField(blank=True, max_length=30)),
                ('question_9', models.CharField(blank=True, max_length=30)),
                ('qr_code', models.TextField()),
                ('is_staff', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('location', models.CharField(max_length=30)),
                ('description', models.TextField()),
                ('question_5', models.CharField(blank=True, max_length=50)),
                ('question_6', models.CharField(blank=True, max_length=50)),
                ('question_7', models.CharField(blank=True, max_length=50)),
                ('question_8', models.CharField(blank=True, max_length=50)),
                ('question_9', models.CharField(blank=True, max_length=50)),
                ('entry', models.ManyToManyField(to='app.Participant')),
            ],
        ),
    ]
